apiVersion: v1
kind: Pod
metadata:
  name: app-pod
spec:
  containers:
  - name: app
    image: deniszierpka/hw-development-app:latest
    ports:
    - containerPort: 5000
    envFrom:
    - configMapRef:
        name: app-config
    volumeMounts:
    - name: logs-volume
      mountPath: /app/logs
  volumes:
  - name: logs-volume
    hostPath:
      path: /var/log/app
      type: DirectoryOrCreate
    # emptyDir: {} # can be used for steps 1-4 instead of hostPath